#!/bin/bash
set -euo pipefail

cd linux_workspace/linux

CROSS_COMPILE=${CROSS_COMPILE:-../toolchain/bin/riscv32-linux-musl-}
JOBS=${JOBS:-8}
MIN_CONFIG=.triathlon_min.config

cat > "${MIN_CONFIG}" <<'EOF'
CONFIG_EXPERT=y
CONFIG_EMBEDDED=y
CONFIG_CC_OPTIMIZE_FOR_SIZE=y
CONFIG_INIT_ENV_ARG_LIMIT=8
CONFIG_LOG_BUF_SHIFT=12
CONFIG_PRINTK=y
CONFIG_BUG=y
CONFIG_BASE_FULL=y
CONFIG_MULTIUSER=y
CONFIG_POSIX_TIMERS=y

CONFIG_32BIT=y
CONFIG_NONPORTABLE=y
CONFIG_ARCH_RV32I=y
CONFIG_MMU=y
CONFIG_PAGE_OFFSET=0xC0000000
CONFIG_RISCV_SBI=y
CONFIG_RISCV_SBI_V01=y
CONFIG_RISCV_ISA_A=y
CONFIG_RISCV_ISA_C=y
CONFIG_RISCV_ISA_FALLBACK=y
CONFIG_TINY_RCU=y
CONFIG_HZ_100=y
CONFIG_SMP=n
CONFIG_FPU=n

CONFIG_CMDLINE_BOOL=y
CONFIG_CMDLINE_FORCE=y
CONFIG_CMDLINE="earlycon=sbi console=ttyS0 root=/dev/ram0"
CONFIG_EFI=n

CONFIG_BLK_DEV_INITRD=y
CONFIG_INITRAMFS_SOURCE="../rootfs ../rootfs_extra.list"
CONFIG_INITRAMFS_COMPRESSION_NONE=y
CONFIG_RD_GZIP=n
CONFIG_RD_BZIP2=n
CONFIG_RD_LZMA=n
CONFIG_RD_XZ=n
CONFIG_RD_LZO=n
CONFIG_RD_LZ4=n
CONFIG_RD_ZSTD=n

CONFIG_BINFMT_ELF=y
CONFIG_BINFMT_SCRIPT=y
CONFIG_FUTEX=y
CONFIG_EPOLL=y
CONFIG_EVENTFD=y
CONFIG_TIMERFD=y
CONFIG_SIGNALFD=y

CONFIG_OF=y
CONFIG_OF_FLATTREE=y
CONFIG_OF_EARLY_FLATTREE=y
CONFIG_OF_ADDRESS=y
CONFIG_OF_IRQ=y
CONFIG_OF_RESERVED_MEM=y

CONFIG_TTY=y
CONFIG_SERIAL_EARLYCON=y
CONFIG_SERIAL_EARLYCON_RISCV_SBI=y
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_CONSOLE=y
CONFIG_SERIAL_OF_PLATFORM=y
CONFIG_SERIAL_8250_NR_UARTS=1
CONFIG_SERIAL_8250_RUNTIME_UARTS=1
CONFIG_VT=n
CONFIG_UNIX98_PTYS=n
CONFIG_LEGACY_PTYS=n

CONFIG_DEVTMPFS=y
CONFIG_DEVTMPFS_MOUNT=y
CONFIG_PROC_FS=y
CONFIG_PROC_SYSCTL=y
CONFIG_SYSFS=y
CONFIG_TMPFS=y
CONFIG_SHMEM=y
CONFIG_TMPFS_POSIX_ACL=n
CONFIG_TMPFS_XATTR=n

CONFIG_NET=n
CONFIG_BLOCK=n
CONFIG_PCI=n
CONFIG_MODULES=n
CONFIG_CGROUPS=n
CONFIG_NAMESPACES=n
CONFIG_BPF_SYSCALL=n
CONFIG_PERF_EVENTS=n
CONFIG_PROFILING=n
CONFIG_KALLSYMS=n
CONFIG_FTRACE=n
CONFIG_DEBUG_KERNEL=n
CONFIG_DEBUG_INFO=n
CONFIG_AUDIT=n
CONFIG_SECURITY=n
CONFIG_INTEGRITY=n
CONFIG_CRYPTO=n
CONFIG_INPUT=n
CONFIG_GPIO_CDEV=n
CONFIG_PINCTRL=n
CONFIG_I2C=n
CONFIG_SPI=n
CONFIG_USB=n
CONFIG_MMC=n
CONFIG_RTC_CLASS=n
CONFIG_WATCHDOG=n
CONFIG_THERMAL=n
CONFIG_CPU_IDLE=n
CONFIG_MEDIA_SUPPORT=n
CONFIG_SOUND=n
CONFIG_DRM=n
CONFIG_VIRTIO=n
CONFIG_FW_LOADER=n
CONFIG_PM=n
CONFIG_SUSPEND=n
CONFIG_HIBERNATION=n
CONFIG_IO_URING=n
EOF

KCONFIG_ALLCONFIG="${MIN_CONFIG}" \
  make ARCH=riscv CROSS_COMPILE="${CROSS_COMPILE}" allnoconfig

./scripts/config --set-str CONFIG_INITRAMFS_SOURCE "../rootfs ../rootfs_extra.list"
./scripts/config --set-str CONFIG_CMDLINE "earlycon=sbi console=ttyS0 root=/dev/ram0"
make ARCH=riscv CROSS_COMPILE="${CROSS_COMPILE}" olddefconfig

for opt in \
  NET BLOCK PCI MODULES CGROUPS NAMESPACES BPF_SYSCALL PERF_EVENTS PROFILING \
  KALLSYMS FTRACE DEBUG_INFO AUDIT SECURITY INTEGRITY CRYPTO \
  INPUT PINCTRL I2C SPI USB MMC RTC_CLASS WATCHDOG THERMAL CPU_IDLE \
  MEDIA_SUPPORT SOUND DRM VIRTIO FW_LOADER PM SUSPEND HIBERNATION IO_URING \
  BLK_DEV_RAM VIRTIO_BLK CDROM FAT_FS ISO9660_FS EXT4_FS; do
  if grep -q "^CONFIG_${opt}=y" .config; then
    echo "[kernel-config] unexpected CONFIG_${opt}=y"
    exit 1
  fi
done

make ARCH=riscv CROSS_COMPILE="${CROSS_COMPILE}" -j"${JOBS}" Image
echo "LINUX KERNEL COMPLETE"
