NAME     := am
SRCS      = $(addprefix src/, $(AM_SRCS))
INC_PATH += $(AM_HOME)/am/src
$(info [DEBUG] AM_SRCS=$(AM_SRCS))
$(info [DEBUG] SRCS=$(SRCS))
include $(AM_HOME)/Makefile
$(info [DEBUG] AM_SRCS=$(AM_SRCS))
$(info [DEBUG] SRCS=$(SRCS))
